global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'api'
    static_configs:
      - targets: ['host.docker.internal:4000']
